"""Unit tests for the SQLite layer (graph/db.py)."""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest

from repo_navigator.graph.db import CURRENT_SCHEMA_VERSION, Database
from repo_navigator.models.edges import Edge, EdgeType
from repo_navigator.models.file_state import FileState
from repo_navigator.models.nodes import Node, NodeType
from repo_navigator.models.option_value import OptionValue, ValueStatus


@pytest.fixture()
def db() -> Database:
    database = Database(":memory:")
    database.init_db()
    return database


def make_module(path: str = "modules/a.nix", **overrides) -> Node:
    defaults = dict(
        id=f"nix:{path}",
        type=NodeType.nix_module,
        name=path,
        path=path,
        lang="nix",
        metadata={"k": "v"},
    )
    defaults.update(overrides)
    return Node(**defaults)


# ---------------------------------------------------------------- lifecycle


class TestInit:
    def test_generation_starts_at_zero(self, db: Database) -> None:
        assert db.get_generation_id() == 0

    def test_inc_generation(self, db: Database) -> None:
        assert db.inc_generation_id() == 1
        assert db.inc_generation_id() == 2
        assert db.get_generation_id() == 2

    def test_schema_version_set(self, db: Database) -> None:
        version = db._conn.execute("PRAGMA user_version").fetchone()[0]
        assert version == CURRENT_SCHEMA_VERSION

    def test_reinit_is_idempotent(self, db: Database) -> None:
        db.upsert_node(make_module())
        db.init_db()  # must not wipe data or fail
        assert db.count_nodes() == 1
        assert db.get_generation_id() == 0


# -------------------------------------------------------------------- nodes


class TestNodes:
    def test_roundtrip_with_metadata(self, db: Database) -> None:
        node = make_module(metadata={"opt_type": "types.bool", "n": 42})
        db.upsert_node(node)
        loaded = db.get_node(node.id)
        # updated_at is regenerated by the DB on write
        assert loaded.model_dump(exclude={"updated_at"}) == node.model_dump(
            exclude={"updated_at"}
        )
        assert loaded.updated_at >= node.updated_at

    def test_get_missing_returns_none(self, db: Database) -> None:
        assert db.get_node("nope") is None

    def test_upsert_updates_but_keeps_created_at(self, db: Database) -> None:
        original = make_module(name="old.nix")
        db.upsert_node(original)

        renamed = original.model_copy(update={"name": "new.nix"})
        db.upsert_node(renamed)

        nodes = db.get_all_nodes()
        assert len(nodes) == 1
        assert nodes[0].name == "new.nix"
        assert nodes[0].created_at == original.created_at

    def test_delete_file_nodes_removes_edges(self, db: Database) -> None:
        a = make_module("modules/a.nix")
        b = make_module("modules/b.nix")
        c = make_module("modules/c.nix")
        for n in (a, b, c):
            db.upsert_node(n)
        db.upsert_edge(
            Edge(id="e1", source=a.id, target=b.id, type=EdgeType.imports)
        )
        db.upsert_edge(
            Edge(id="e2", source=c.id, target=b.id, type=EdgeType.imports)
        )

        db.delete_file_nodes(a.path)

        assert db.get_node(a.id) is None
        assert db.get_edge("e1") is None  # source deleted -> edge gone
        assert db.get_edge("e2") is not None  # untouched pair survives
        assert db.count_nodes() == 2

    def test_count_nodes(self, db: Database) -> None:
        assert db.count_nodes() == 0
        db.upsert_node(make_module())
        assert db.count_nodes() == 1


# -------------------------------------------------------------------- edges


class TestEdges:
    def test_roundtrip(self, db: Database) -> None:
        a, b = make_module("a.nix"), make_module("b.nix")
        db.upsert_node(a)
        db.upsert_node(b)
        edge = Edge(
            id="imports:a->b",
            source=a.id,
            target=b.id,
            type=EdgeType.imports,
            metadata={"line": 5},
            weight=2.0,
        )
        db.upsert_edge(edge)
        assert db.get_edge(edge.id) == edge
        assert db.get_all_edges() == [edge]

    def test_edge_requires_existing_endpoints(self, db: Database) -> None:
        with pytest.raises(sqlite3.IntegrityError):
            db.upsert_edge(
                Edge(id="x", source="ghost", target="also-ghost",
                     type=EdgeType.imports)
            )

    def test_get_edges_for_node_both_directions(self, db: Database) -> None:
        a = make_module("a.nix")
        b = make_module("b.nix")
        c = make_module("c.nix")
        for n in (a, b, c):
            db.upsert_node(n)
        e_ab = Edge(id="e_ab", source=a.id, target=b.id, type=EdgeType.imports)
        e_cb = Edge(id="e_cb", source=c.id, target=b.id, type=EdgeType.imports)
        db.upsert_edge(e_ab)
        db.upsert_edge(e_cb)

        found = {e.id for e in db.get_edges_for_node(b.id)}
        assert found == {"e_ab", "e_cb"}

    def test_get_edges_for_file_ownership_by_source(self, db: Database) -> None:
        a = make_module("modules/a.nix")
        b = make_module("modules/b.nix")
        db.upsert_node(a)
        db.upsert_node(b)
        owned = Edge(id="owned", source=a.id, target=b.id, type=EdgeType.imports)
        foreign = Edge(id="foreign", source=b.id, target=a.id, type=EdgeType.imports)
        db.upsert_edge(owned)
        db.upsert_edge(foreign)

        assert [e.id for e in db.get_edges_for_file(a.path)] == ["owned"]


# --------------------------------------------------------------- file_state


class TestFileState:
    def test_roundtrip(self, db: Database) -> None:
        fs = FileState(
            path="flake.nix",
            lang="nix",
            content_hash="abc",
            ast_hash="def",
            merkle_hash="123",
            detail_level="full",
        )
        db.upsert_file_state(fs)
        assert db.get_file_state("flake.nix") == fs

    def test_dirty_flags(self, db: Database) -> None:
        fs = FileState(path="a.nix", lang="nix", content_hash="h")
        db.upsert_file_state(fs)
        assert db.get_dirty_files() == []

        db.mark_dirty("a.nix")
        assert db.get_dirty_files() == ["a.nix"]

        db.mark_clean("a.nix")
        assert db.get_dirty_files() == []

    def test_get_missing_state(self, db: Database) -> None:
        assert db.get_file_state("ghost") is None


# ------------------------------------------------------- flake_inputs/packages


class TestAuxTables:
    def test_flake_inputs(self, db: Database) -> None:
        db.upsert_flake_input("nixpkgs", "github:NixOS/nixpkgs", "rev1")
        db.upsert_flake_input("nixpkgs", "github:NixOS/nixpkgs", "rev2")
        inputs = db.get_flake_inputs()
        assert inputs == [{"name": "nixpkgs", "url": "github:NixOS/nixpkgs", "rev": "rev2"}]

    def test_packages(self, db: Database) -> None:
        db.upsert_package("ripgrep", "ripgrep", "14.1.0", "/nix/store/rg", {"license": "MIT"})
        pkgs = db.get_packages()
        assert pkgs[0]["attribute"] == "ripgrep"
        assert pkgs[0]["meta"] == {"license": "MIT"}

    def test_package_upsert_preserves_used_by(self, db: Database) -> None:
        db._conn.execute(
            "INSERT INTO package_index (attribute, used_by, first_seen, last_updated)"
            " VALUES ('rg', '[\"host1\"]', '2026-01-01', '2026-01-01')"
        )
        db._conn.commit()
        db.upsert_package("rg", "ripgrep", "14.1.0", None, {})
        row = db._conn.execute(
            "SELECT used_by FROM package_index WHERE attribute='rg'"
        ).fetchone()
        assert row[0] == '["host1"]'


# ------------------------------------------------------------ option_values


class TestOptionValues:
    def test_roundtrip(self, db: Database) -> None:
        ov = OptionValue(
            key="k1",
            expr="config.services.nginx.enable",
            value_json=True,
            status=ValueStatus.ok,
            source_rev="abc123",
        )
        db.upsert_option_value(ov)
        assert db.get_option_value("k1") == ov

    def test_invalidate_matching_exprs_go_stale(self, db: Database) -> None:
        hit = OptionValue(key="hit", expr="config.services.nginx.enable")
        miss = OptionValue(key="miss", expr="config.themes.font")
        for ov in (hit, miss):
            db.upsert_option_value(ov)

        db.invalidate_option_values(["modules/services/nginx.nix"])

        assert db.get_option_value("hit").status is ValueStatus.stale
        assert db.get_option_value("miss").status is ValueStatus.ok

    def test_invalidate_all(self, db: Database) -> None:
        db.upsert_option_value(OptionValue(key="a", expr="x.y"))
        db.upsert_option_value(OptionValue(key="b", expr="p.q"))
        db.invalidate_all_option_values()
        assert db.get_option_value("a").status is ValueStatus.stale
        assert db.get_option_value("b").status is ValueStatus.stale

    def test_empty_paths_noop(self, db: Database) -> None:
        db.upsert_option_value(OptionValue(key="a", expr="x.y"))
        db.invalidate_option_values([])
        assert db.get_option_value("a").status is ValueStatus.ok


# ------------------------------------------------------------------- search


class TestFts5:
    def test_search_finds_by_name_token(self, db: Database) -> None:
        opt = Node(
            id="nix_option:services.nginx.enable",
            type=NodeType.nix_option,
            name="services.nginx.enable",
        )
        db.upsert_node(opt)
        results = db.search_fts5("nginx")
        assert [n.id for n in results] == [opt.id]

    def test_search_respects_limit_and_multi_tokens(self, db: Database) -> None:
        for i in range(3):
            db.upsert_node(
                Node(
                    id=f"o{i}",
                    type=NodeType.nix_option,
                    name=f"services.nginx.enable.opt{i}",
                )
            )
        hits = db.search_fts5("nginx enable", limit=2)  # tokens AND-ed
        assert len(hits) == 2

    def test_search_synced_on_update_and_delete(self, db: Database) -> None:
        node = Node(id="x1", type=NodeType.nix_function, name="mkService")
        db.upsert_node(node)
        assert db.search_fts5("mkservice")  # case-insensitive

        db.upsert_node(node.model_copy(update={"name": "makeService"}))
        assert db.search_fts5("makeservice")
        assert not db.search_fts5("mkservice")

        db.delete_file_nodes(None)  # no-op for NULL paths
        db._conn.execute("DELETE FROM nodes WHERE id='x1'")
        db._conn.commit()
        assert not db.search_fts5("makeservice")

    def test_search_garbage_query_is_safe(self, db: Database) -> None:
        assert db.search_fts5('"unbalanced') == []
        assert db.search_fts5("   ") == []


# -------------------------------------------------------------- persistence


class TestPersistence:
    def test_survives_reopen_and_reinit(self, tmp_path: Path) -> None:
        db_path = tmp_path / ".repo-navigator.db"
        first = Database(db_path)
        first.init_db()
        first.upsert_node(make_module("persist.nix"))
        first.inc_generation_id()
        first.close()

        second = Database(db_path)
        second.init_db()
        assert second.count_nodes() == 1
        assert second.get_generation_id() == 1
        assert second.get_node("nix:persist.nix") is not None
        second.close()

    def test_wal_enabled_on_file_db(self, tmp_path: Path) -> None:
        db = Database(tmp_path / "w.db")
        db.init_db()
        mode = db._conn.execute("PRAGMA journal_mode").fetchone()[0]
        assert mode.lower() == "wal"
        db.close()
